mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4
  db: gvb_db
  user: root
  password: "123456"
  log_level: dev
logger:
  level: info
  prefix: '[gvd]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
site_info:
  create_at: "2023-02-15"
  title: LPH的个人博客
  email: 2337002922@qq.com
  slogan: gvd博客
  github_url: https://github.com/lphmisayo
jwt:
  secret: "lph"
  expire: 48
  issuer: lph
qq:
  app_id: "xx"
  key: xx
  redirect: http://xx.xx.com/login?flag=qq
qiniu:
  access_key: UMM-xx-FdRIf-xx
  secret_key: xx
  bucket: lphmisaka
  cdn: xx://xx.xx.com/
  zone: xx
  size: 5
email:
  host: xxxx.qq.com
  port: 465
  user: xxx@qq.com
  password: xxx
  default_from_email: lphmisaka
  use_ssl: xx
  user_tls: xx

