mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4
  db: gvb_db
  user: root
  password: "123456"
  log_level: dev
logger:
  level: info
  prefix: '[gvd]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
site_info:
  create_at: "2023-02-15"
  title: LPH的个人博客
  email: 2337002922@qq.com
  slogan: gvd博客
  github_url: https://github.com/lphmisayo
QQ:
  app_id: xxxx.xxxx
  key: testPw
  redirect: testRe
email:
  host: xxx.xx.x.x
  port: 330
  user: 2337002922@qq.com
  password: test
  default_from_email: https://github.com/lphmisayo
  use_ssl: true
  user_tls: false
qiniu:
  enable: false
  access_key: UMM-xx-FdRIf-xx
  secret_key: xx
  bucket: lphmisaka
  cdn: xx://xx.xx.com/
  zone: xx
  size: 5
jwt:
  secret: lph
  expire: 48
  issuer: lph
local:
  path: uploads/file
  store_path: uploads/file
  size: 2